---
- hosts: all
  remote_user: shk
  become: yes
  become_method: sudo
  vars_files:
    - ../vars/apache_install_vars.yml
  tasks:
  - name: Install httpd on CentOS7 node
    yum:
      name: httpd
      state: present
    when:
      - ansible_os_family == "RedHat"
  - name: ensure apache is running
    service:
      name: httpd
      state: started
    when:
      - ansible_os_family == "RedHat"
  - name: write the apache config file
    template:
      src: ../files/httpd.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - restart apache
    when:
      - ansible_os_family == "RedHat"
  - name: Install httpd on ubuntu node
    apt:
      name: apache2
      state: present
    when:
      - ansible_os_family == "Debian"
  - name: ensure apache2 is running on ubuntu
    service:
      name: apache2
      state: started
    when:
      - ansible_os_family == "Debian"
  - name: write the apache2 config file
    template:
      src: ../files/apache2_ports.j2
      dest: /etc/apache2/ports.conf
    notify:
    - restart apache2
    when:
      - ansible_os_family == "Debian"
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
    - name: restart apache2
      service:
        name: apache2
        state: restarted
